baseUrl=https://tms-api.stage.oorjaa.tech
username=suyog.patil@oorjaa.tech
password=suyog@2189
tenantId=1
visibilityScope=TMS_WEB
db.url=jdbc:mysql://13.205.108.207:3306
db.username=suyog-patil
db.password=iOpgt*45hPie
